- hosts: all
  become: true
  vars_files:
    - vars/restart.yml
  tasks:
    - name: Restart service "{{ service2restart }}" in all cases
      service:
        name: "{{ service2restart }}"
        state: restarted

